# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, check
# build.gradle files instead.

# When configured, Gradle will run in transactional mode with remote build cache enabled.
#org.gradle.caching=true

# AndroidX package structure to make it clearer which packages are being used
android.useAndroidX=true

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Enable the new kotlin DSL lazy property assignment for androidComponents extension.
# This is an unstable API that may change.
android.experimental.enableNewApiLevelDerivation=true
